api_platform:

  defaults:
    pagination_client_enabled: true
    pagination_items_per_page: 5
    pagination_client_items_per_page: true

  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  collection:
    pagination:
      enabled: false
      items_per_page_parameter_name: "count"

